baseURL = "https://www.osteopathyny.com/"
languageCode = "en"
title = "Melissa Ventimiglia, D.O."

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 10

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  tag = "tags"
